// ── Field Schemas for Developer Reference ─────────────────────────────────
// Each entry: { field, type, required, description, children? }
const FIELD_SCHEMAS = {
  'CH-001': [
    { field: 'series', type: 'Array<{ name, data: [{x, y}], color? }>', required: true, desc: 'Array of line series with data points' },
    { field: 'series[].name', type: 'string', required: true, desc: 'Legend label for the series' },
    { field: 'series[].data', type: 'Array<{ x: string, y: number }>', required: true, desc: 'Data points with x (category) and y (value)' },
    { field: 'series[].color', type: 'string', required: false, desc: 'Hex color override (default: palette)' },
    { field: 'yAxis', type: '{ label?, format? }', required: false, desc: 'Y-axis configuration' },
    { field: 'yAxis.format', type: '"currency" | "percent" | "number"', required: false, desc: 'Value formatting' },
    { field: 'annotations', type: 'Array<{ x, label }>', required: false, desc: 'Vertical reference lines' },
  ],
  'CH-002': [
    { field: 'data', type: 'Array<{ category, value, color? }>', required: true, desc: 'Bar data with category labels' },
    { field: 'series', type: 'Array<{ name, color? }>', required: false, desc: 'Grouped/stacked series definitions' },
    { field: 'orientation', type: '"vertical" | "horizontal"', required: false, desc: 'Bar layout direction (default: vertical)' },
    { field: 'grouping', type: '"grouped" | "stacked"', required: false, desc: 'Multi-series grouping mode' },
    { field: 'yAxis', type: '{ label?, format? }', required: false, desc: 'Y-axis configuration' },
  ],
  'CH-003': [
    { field: 'segments', type: 'Array<{ label, value, color? }>', required: true, desc: 'Pie/donut slices' },
    { field: 'centerLabel', type: '{ value, subtitle }', required: false, desc: 'Center text for donut' },
    { field: 'showLegend', type: 'boolean', required: false, desc: 'Show legend beside chart (default: true)' },
  ],
  'CH-004': [
    { field: 'regions', type: 'Array<{ regionName, value }>', required: true, desc: 'Geographic regions with values' },
    { field: 'metric', type: 'string', required: true, desc: 'Metric label displayed' },
    { field: 'colorScale', type: '{ min, max }', required: false, desc: 'Hex color range for heatmap' },
    { field: 'mapType', type: '"state" | "region"', required: false, desc: 'US state map or region bubble (default: state)' },
  ],
  'CH-005': [
    { field: 'stages', type: 'Array<{ name, value, conversionRate? }>', required: true, desc: 'Funnel stages top to bottom' },
    { field: 'metric', type: 'string', required: true, desc: 'Unit label (e.g. "Leads")' },
  ],
  'CH-006': [
    { field: 'value', type: 'number', required: true, desc: 'Current gauge value' },
    { field: 'max', type: 'number', required: true, desc: 'Maximum gauge value' },
    { field: 'label', type: 'string', required: true, desc: 'Gauge label text' },
    { field: 'format', type: '"currency" | "percent" | "number"', required: false, desc: 'Value display format' },
    { field: 'thresholds', type: 'Array<{ value, color, label }>', required: false, desc: 'Color bands at specific values' },
  ],
  'CH-007': [
    { field: 'data', type: 'Array<number>', required: true, desc: 'Numeric data points for the sparkline' },
    { field: 'color', type: 'string', required: false, desc: 'Line color (default: #5b6af0)' },
    { field: 'height', type: 'number', required: false, desc: 'Chart height in px (default: 40)' },
    { field: 'showEndDot', type: 'boolean', required: false, desc: 'Dot on latest data point (default: true)' },
  ],
  'CH-008': [
    { field: 'data', type: 'Array<{ date: "YYYY-MM-DD", value: number }>', required: true, desc: 'Daily values for the heatmap' },
    { field: 'colorScale', type: '{ min, max }', required: false, desc: 'Hex color range' },
    { field: 'period', type: 'string', required: false, desc: 'Period label (e.g. "month")' },
  ],
  'CH-009': [
    { field: 'series', type: 'Array<{ name, data: [{x, y}], color? }>', required: true, desc: 'Stacked area series' },
    { field: 'yAxis', type: '{ label?, format? }', required: false, desc: 'Y-axis configuration' },
  ],
  'CH-010': [
    { field: 'steps', type: 'Array<{ label, value, type }>', required: true, desc: 'Waterfall steps' },
    { field: 'steps[].type', type: '"total" | "increase" | "decrease"', required: true, desc: 'Step type for coloring' },
    { field: 'format', type: '"currency" | "number"', required: false, desc: 'Value display format' },
  ],
  'CH-011': [
    { field: 'entries', type: 'Array<{ rank?, label, value, meta? }>', required: true, desc: 'Ranked leaderboard entries' },
    { field: 'metric', type: 'string', required: true, desc: 'Metric being ranked (e.g. "Revenue")' },
    { field: 'format', type: '"currency" | "number"', required: false, desc: 'Value display format' },
  ],
  'UW-001': [
    { field: 'label', type: 'string', required: true, desc: 'Metric name' },
    { field: 'value', type: 'number', required: true, desc: 'Primary value' },
    { field: 'format', type: '"currency" | "percent" | "count"', required: false, desc: 'Value formatting' },
    { field: 'trend', type: '{ direction, percent, period }', required: false, desc: 'Trend arrow with percent change' },
    { field: 'trend.direction', type: '"up" | "down"', required: true, desc: 'Trend direction' },
    { field: 'comparison', type: '{ label, value }', required: false, desc: 'Comparison benchmark' },
    { field: 'sparkline', type: 'Array<number>', required: false, desc: 'Inline sparkline data' },
  ],
  'UW-002': [
    { field: 'title', type: 'string', required: false, desc: 'Row heading' },
    { field: 'cards', type: 'Array<MetricCard>', required: true, desc: 'Array of metric card data (same schema as UW-001)' },
  ],
  'UW-003': [
    { field: 'entityType', type: 'string', required: true, desc: 'Entity type label (e.g. "order", "customer")' },
    { field: 'header', type: '{ id, title, status? }', required: true, desc: 'Card header with title and optional status' },
    { field: 'header.status', type: '{ label, variant }', required: false, desc: 'StatusBadge in header' },
    { field: 'sections', type: 'Array<{ title, fields: [{key, value}] }>', required: true, desc: 'Collapsible detail sections' },
    { field: 'actions', type: 'Array<Action>', required: false, desc: 'Action buttons at bottom' },
  ],
  'UW-004': [
    { field: 'columns', type: 'Array<{ key, label, type, sortable? }>', required: true, desc: 'Column definitions' },
    { field: 'columns[].type', type: '"string" | "badge" | "currency" | "date"', required: true, desc: 'Cell render type' },
    { field: 'rows', type: 'Array<Object>', required: true, desc: 'Row data keyed by column.key' },
    { field: 'pagination', type: '{ page, pageSize, total }', required: false, desc: 'Pagination footer' },
    { field: 'emptyState', type: 'string', required: false, desc: 'Text shown when no rows' },
  ],
  'UW-005': [
    { field: 'stages', type: 'Array<{ id, name, count, color? }>', required: true, desc: 'Kanban column definitions' },
    { field: 'cards', type: 'Array<{ id, stageId, title, subtitle?, badges?, meta? }>', required: true, desc: 'Cards placed in stages by stageId' },
  ],
  'UW-006': [
    { field: 'label', type: 'string', required: true, desc: 'Badge text' },
    { field: 'variant', type: '"success"|"warning"|"danger"|"info"|"neutral"|"special"', required: true, desc: 'Color variant' },
    { field: 'size', type: '"sm" | "md"', required: false, desc: 'Badge size (default: md)' },
  ],
  'UW-007': [
    { field: 'profile', type: '{ name, customerId, type, salesRep, priceList, territory }', required: true, desc: 'Customer profile data' },
    { field: 'metrics', type: '{ cards: Array<MetricCard> }', required: true, desc: 'KPI cards (same schema as UW-001)' },
    { field: 'salesTrend', type: 'Array<number>', required: false, desc: 'Sparkline data for revenue trend' },
    { field: 'recentOrders', type: 'Array<{ id, date, value, status }>', required: false, desc: 'Latest orders list' },
    { field: 'openTasks', type: 'Array<{ title, due }>', required: false, desc: 'Pending tasks' },
    { field: 'riskIndicator', type: '{ level, reason }', required: false, desc: 'Churn risk indicator' },
    { field: 'riskIndicator.level', type: '"healthy"|"watch"|"at_risk"|"churned"', required: true, desc: 'Risk level' },
  ],
  'UW-008': [
    { field: 'skuId', type: 'string', required: true, desc: 'Product SKU identifier' },
    { field: 'name', type: 'string', required: true, desc: 'Product name' },
    { field: 'price', type: '{ base, sale?, currency? }', required: true, desc: 'Pricing info' },
    { field: 'availability', type: '{ inStock, status, backorderAllowed? }', required: true, desc: 'Stock status' },
    { field: 'availability.status', type: '"in_stock"|"low_stock"|"out_of_stock"', required: true, desc: 'Stock level enum' },
    { field: 'labels', type: 'Array<string>', required: false, desc: 'Badge labels (e.g. "New Arrival")' },
    { field: 'actions', type: 'Array<Action>', required: false, desc: 'Action buttons' },
  ],
  'UW-009': [
    { field: 'products', type: 'Array<ProductCard>', required: true, desc: 'Array of product data (same schema as UW-008)' },
    { field: 'total', type: 'number', required: false, desc: 'Total product count' },
    { field: 'pagination', type: '{ page, pageSize, total }', required: false, desc: 'Pagination info' },
  ],
  'UW-010': [
    { field: 'entries', type: 'Array<{ timestamp, actor, action, detail? }>', required: true, desc: 'Chronological event entries' },
    { field: 'entries[].timestamp', type: 'ISO 8601 string', required: true, desc: 'Event timestamp' },
    { field: 'entries[].actor', type: 'string', required: true, desc: 'Person or system that triggered event' },
    { field: 'entries[].action', type: 'string', required: true, desc: 'Action description' },
  ],
  'UW-011': [
    { field: 'items', type: 'Array<{ title, subtitle?, badge?, meta? }>', required: true, desc: 'List items' },
    { field: 'items[].badge', type: '{ label, variant }', required: false, desc: 'StatusBadge for item' },
    { field: 'maxVisible', type: 'number', required: false, desc: 'Items shown before "show more" (default: 5)' },
    { field: 'emptyState', type: 'string', required: false, desc: 'Text when no items' },
  ],
  'UW-012': [
    { field: 'customer', type: '{ name, id }', required: true, desc: 'Customer info' },
    { field: 'priceList', type: 'string', required: false, desc: 'Applied price list name' },
    { field: 'items', type: 'Array<{ sNo, skuId, name, price, qty, total, cft }>', required: true, desc: 'Line items' },
    { field: 'container', type: '{ cftCapacity, totalCft, fillPercent }', required: false, desc: 'Container fill status' },
    { field: 'summary', type: '{ orderTotal, discount?, shipping?, total }', required: false, desc: 'Order totals' },
    { field: 'actions', type: 'Array<Action>', required: false, desc: 'Action buttons' },
  ],
  'UW-013': [
    { field: 'filters', type: 'Array<{ field, operator, value, removable? }>', required: true, desc: 'Active filter chip data' },
    { field: 'filters[].field', type: 'string', required: true, desc: 'Filter field name' },
    { field: 'filters[].operator', type: 'string', required: true, desc: 'Comparison operator (e.g. "is", ">")' },
    { field: 'filters[].value', type: 'string', required: true, desc: 'Filter value' },
    { field: 'filters[].removable', type: 'boolean', required: false, desc: 'Show × to remove (default: true)' },
  ],
  'UW-014': [
    { field: 'summary', type: 'string', required: true, desc: 'Agent reasoning summary text' },
    { field: 'steps', type: 'Array<{ stepNumber, action, detail?, dataSource? }>', required: true, desc: 'Reasoning steps' },
    { field: 'dataAccessed', type: 'Array<string>', required: false, desc: 'Data sources accessed' },
    { field: 'timestamp', type: 'ISO 8601 string', required: false, desc: 'When reasoning was generated' },
    { field: 'expandable', type: 'boolean', required: false, desc: 'Allow expanding steps (default: true)' },
  ],
  'UW-015': [
    { field: 'items', type: 'Array<{ label, metrics: [{key, value}] }>', required: true, desc: 'Comparison columns' },
    { field: 'highlightWinner', type: 'boolean', required: false, desc: 'Highlight best value per row (default: true)' },
  ],
  'UW-016': [
    { field: 'type', type: '"info" | "warning" | "error" | "success"', required: true, desc: 'Alert severity' },
    { field: 'title', type: 'string', required: true, desc: 'Alert heading' },
    { field: 'body', type: 'string', required: true, desc: 'Alert message body' },
    { field: 'dismissible', type: 'boolean', required: false, desc: 'Allow dismissing (default: false)' },
  ],
  'UW-017': [
    { field: 'fileName', type: 'string', required: true, desc: 'File name' },
    { field: 'fileType', type: 'string', required: true, desc: 'File extension (pdf, png, xlsx, etc.)' },
    { field: 'fileSize', type: 'string', required: true, desc: 'Human-readable file size' },
    { field: 'uploadedDate', type: 'ISO 8601 string', required: false, desc: 'Upload timestamp' },
    { field: 'actions', type: 'Array<Action>', required: false, desc: 'Action buttons' },
  ],
  'UW-018': [
    { field: 'roleName', type: 'string', required: true, desc: 'Role name heading' },
    { field: 'modules', type: 'Array<{ moduleName, permissions }>', required: true, desc: 'Module permission groups' },
    { field: 'modules[].permissions', type: 'Array<{ name, enabled }>', required: true, desc: 'Permission toggles per module' },
  ],
  'UW-019': [
    { field: 'operation', type: '"import" | "export"', required: true, desc: 'Operation type' },
    { field: 'entity', type: 'string', required: true, desc: 'Entity being imported/exported' },
    { field: 'status', type: '"in_progress"|"completed"|"failed"|"cancelled"', required: true, desc: 'Current status' },
    { field: 'progress', type: 'number (0–100)', required: true, desc: 'Progress percentage' },
    { field: 'details', type: '{ totalRows, processedRows, errorCount?, fileName? }', required: false, desc: 'Detailed progress info' },
    { field: 'errors', type: 'Array<string>', required: false, desc: 'Error messages list' },
  ],
  'UW-020': [
    { field: 'segmentName', type: 'string', required: true, desc: 'Segment name' },
    { field: 'segmentType', type: 'string', required: true, desc: 'Segment type label' },
    { field: 'includeRules', type: 'Array<{ condition, operator, values[] }>', required: true, desc: 'Inclusion rules' },
    { field: 'excludeRules', type: 'Array<{ condition, operator, values[] }>', required: false, desc: 'Exclusion rules' },
    { field: 'matchMode', type: '"all" | "any"', required: false, desc: 'Rule matching mode' },
    { field: 'memberCount', type: 'number', required: false, desc: 'Matching member count' },
  ],
  'UW-021': [
    { field: 'name', type: 'string', required: true, desc: 'Discount name' },
    { field: 'type', type: 'string', required: true, desc: 'Discount type (e.g. "product")' },
    { field: 'status', type: '{ label, variant }', required: false, desc: 'Status badge' },
    { field: 'application', type: 'string', required: false, desc: 'How the discount is applied' },
    { field: 'channels', type: 'Array<string>', required: false, desc: 'Sales channels' },
    { field: 'discountValue', type: '{ type, value, tiers? }', required: false, desc: 'Discount value and tiers' },
    { field: 'schedule', type: '{ start, end }', required: false, desc: 'Active date range' },
  ],
  'UW-022': [
    { field: 'workflowName', type: 'string', required: true, desc: 'Workflow name' },
    { field: 'status', type: '{ label, variant }', required: false, desc: 'Overall status badge' },
    { field: 'startTime', type: 'ISO 8601 string', required: true, desc: 'Workflow start time' },
    { field: 'endTime', type: 'ISO 8601 string', required: false, desc: 'Workflow end time' },
    { field: 'nodes', type: 'Array<{ name, type, status }>', required: true, desc: 'Pipeline nodes' },
    { field: 'nodes[].status', type: '"completed"|"running"|"failed"|"pending"|"skipped"', required: true, desc: 'Node status' },
  ],
  'UW-023': [
    { field: 'name', type: 'string', required: true, desc: 'Payment name' },
    { field: 'customer', type: 'string', required: true, desc: 'Customer name' },
    { field: 'status', type: '{ label, variant }', required: false, desc: 'Payment status badge' },
    { field: 'amount', type: '{ payable, recurring?, currency }', required: true, desc: 'Payment amounts' },
    { field: 'frequency', type: 'string', required: true, desc: 'Billing frequency (e.g. "Monthly")' },
    { field: 'dates', type: '{ start, nextBilling, end }', required: true, desc: 'Billing timeline dates' },
    { field: 'paymentMethod', type: 'string', required: false, desc: 'Payment method display string' },
  ],
};
